# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Anastasia Antsiferova's Blog
tagline:          'keep_talking'
description:      'Student at Lomonosov MSU'
url:              aantsiferova.github.io
baseurl:          /

paginate:         5

github:
  repo:           https://github.com/aantsiferova

author:
  name:           Anastasia Antsiferova           
  email:          aantsiferova@graphics.cs.msu.ru