# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Anastasia Antsiferova
tagline:          tagline
description:      description
url:              http://vk.com/keep_talking
baseurl:          /

paginate:         5

github:
  repo:           https://github.com/poole/hyde
