# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Anastasia Antsiferova
tagline:          Student at Lomonosov MSU
url:              vk.com/keep_talking

paginate:         5

github:
  repo:           https://github.com/aantsiferova
