# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Anastasia Antsiferova
tagline:          tagline
description:      description
url:              http://aantsiferova.github.io
baseurl:          /

paginate:         5

github:
  repo:           https://github.com/aantsiferova
