# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Anastasia Antsiferova
tagline:          'keep_talking'
description:      'Student at Lomonosov MSU'
url:              http://aantsiferova.github.io
baseurl:          /

paginate:         5

github:
  repo:           https://github.com/aantsiferova
